CREATE TYPE "user_status" AS ENUM (
  'active',
  'inactive',
  'banned'
);

CREATE TYPE "otp_purpose" AS ENUM (
  'confirm_account',
  'reset_password'
);

CREATE TYPE "venue_status" AS ENUM (
  'pending',
  'approved',
  'blocked'
);

CREATE TYPE "space_type" AS ENUM (
  'private_office',
  'meeting_room',
  'desk'
);

CREATE TYPE "verification_status" AS ENUM (
  'pending',
  'approved',
  'rejected'
);

CREATE TYPE "price_unit" AS ENUM (
  'hour',
  'day',
  'month'
);

CREATE TYPE "booking_status" AS ENUM (
  'pending_payment',
  'confirmed',
  'cancelled',
  'completed'
);

CREATE TYPE "payment_method" AS ENUM (
  'vnpay',
  'momo',
  'stripe'
);

CREATE TYPE "payment_status" AS ENUM (
  'pending',
  'success',
  'failed',
  'refunded'
);

CREATE TYPE "notification_type" AS ENUM (
  'booking_status_changed',
  'account_activated',
  'payment_success',
  'payment_failed',
  'new_message',
  'venue_approved',
  'venue_blocked'
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "users_roles" (
  "user_id" bigint,
  "role_id" integer,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "full_name" varchar,
  "phone" varchar,
  "avatar_url" varchar,
  "is_verified" boolean DEFAULT false,
  "status" user_status NOT NULL DEFAULT 'inactive',
  "language" varchar(5) DEFAULT 'vi',
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "refresh_tokens" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "token_hash" varchar NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used_at" timestamp,
  "revoked" boolean DEFAULT false,
  "created_at" timestamp
);

CREATE TABLE "otp_verifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "otp_code" varchar(6) NOT NULL,
  "purpose" otp_purpose NOT NULL,
  "expires_at" timestamp NOT NULL,
  "used_at" timestamp,
  "created_at" timestamp
);

CREATE TABLE "venues" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" bigint NOT NULL,
  "name" varchar NOT NULL,
  "description" text,
  "street" varchar,
  "city" varchar NOT NULL,
  "latitude" decimal(9,6),
  "longitude" decimal(9,6),
  "status" venue_status NOT NULL DEFAULT 'pending',
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "venue_managers" (
  "venue_id" bigint,
  "user_id" bigint,
  PRIMARY KEY ("venue_id", "user_id")
);

CREATE TABLE "amenities" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "venue_amenities" (
  "venue_id" bigint,
  "amenity_id" bigint,
  PRIMARY KEY ("venue_id", "amenity_id")
);

CREATE TABLE "user_identity_verifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "identity_card_url" varchar NOT NULL,
  "status" verification_status NOT NULL DEFAULT 'pending',
  "reviewed_by" bigint,
  "reviewed_at" timestamp,
  "rejection_reason" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "venue_business_verifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venue_id" bigint NOT NULL,
  "business_license_url" varchar NOT NULL,
  "status" verification_status NOT NULL DEFAULT 'pending',
  "reviewed_by" bigint,
  "reviewed_at" timestamp,
  "rejection_reason" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "space_prices" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "space_id" bigint NOT NULL,
  "unit" price_unit NOT NULL,
  "price" numeric(12,2) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "spaces" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venue_id" bigint NOT NULL,
  "name" varchar NOT NULL,
  "type" space_type NOT NULL,
  "capacity" integer,
  "description" text,
  "open_time" time,
  "close_time" time,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "conversations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venue_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" bigint NOT NULL,
  "sender_id" bigint NOT NULL,
  "content" text NOT NULL,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp
);

CREATE TABLE "bookings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "space_id" bigint NOT NULL,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "price_unit" price_unit NOT NULL,
  "total_price" numeric(12,2) NOT NULL,
  "status" booking_status NOT NULL DEFAULT 'pending_payment',
  "payment_deadline" timestamp NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" bigint NOT NULL,
  "amount" numeric(12,2) NOT NULL,
  "method" payment_method NOT NULL,
  "status" payment_status NOT NULL DEFAULT 'pending',
  "transaction_ref" varchar,
  "paid_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "type" notification_type NOT NULL,
  "title" varchar NOT NULL,
  "content" text,
  "reference_id" bigint,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp
);

CREATE INDEX ON "refresh_tokens" ("user_id");

CREATE INDEX ON "refresh_tokens" ("expires_at");

CREATE INDEX ON "otp_verifications" ("user_id");

CREATE INDEX ON "otp_verifications" ("user_id", "purpose");

CREATE INDEX ON "venues" ("owner_id");

CREATE INDEX ON "venues" ("city");

CREATE INDEX ON "venues" ("latitude", "longitude");

CREATE INDEX ON "user_identity_verifications" ("user_id", "created_at");

CREATE INDEX ON "venue_business_verifications" ("venue_id", "created_at");

CREATE UNIQUE INDEX ON "space_prices" ("space_id", "unit");

CREATE INDEX ON "spaces" ("venue_id");

CREATE INDEX ON "spaces" ("type");

CREATE UNIQUE INDEX ON "conversations" ("venue_id", "user_id");

CREATE INDEX ON "messages" ("conversation_id", "created_at");

CREATE INDEX ON "bookings" ("space_id", "start_time", "end_time");

CREATE INDEX ON "bookings" ("user_id");

CREATE INDEX ON "bookings" ("status");

CREATE INDEX ON "bookings" ("status", "payment_deadline");

CREATE INDEX ON "bookings" ("status", "end_time");

CREATE INDEX ON "payments" ("booking_id");

CREATE INDEX ON "payments" ("transaction_ref");

CREATE INDEX ON "notifications" ("user_id", "is_read");

CREATE INDEX ON "notifications" ("user_id", "created_at");

ALTER TABLE "users_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "otp_verifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venues" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venue_managers" ADD FOREIGN KEY ("venue_id") REFERENCES "venues" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venue_managers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venue_amenities" ADD FOREIGN KEY ("venue_id") REFERENCES "venues" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venue_amenities" ADD FOREIGN KEY ("amenity_id") REFERENCES "amenities" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_identity_verifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_identity_verifications" ADD FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venue_business_verifications" ADD FOREIGN KEY ("venue_id") REFERENCES "venues" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venue_business_verifications" ADD FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "space_prices" ADD FOREIGN KEY ("space_id") REFERENCES "spaces" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "spaces" ADD FOREIGN KEY ("venue_id") REFERENCES "venues" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversations" ADD FOREIGN KEY ("venue_id") REFERENCES "venues" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookings" ADD FOREIGN KEY ("space_id") REFERENCES "spaces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- Chống trùng lịch đặt chỗ cho cùng 1 space
CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE "bookings" ADD CONSTRAINT no_overlap
  EXCLUDE USING gist (
    space_id WITH =,
    tsrange(start_time, end_time) WITH &&
  ) WHERE (status IN ('pending_payment', 'confirmed'));